### PR TITLE
log  info, as it's more appropriate

### PR DESCRIPTION
**Pull request by Nesze**
https://github.com/Financial-Times/publish-availability-monitor/issues/112

cc: @ppragnya

### CODE REVIEW

**Comment by Nesze** [comment]
@bogdanguranda @kovacshuni @radutudor: any takers for this?

**Comment by kovacshuni** [comment]
http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

**Comment by kovacshuni** [comment]
We discussed, we would not log for 200, or 404 and remain with warn logging for other status codes. The reference says `NoSuchKey` gives 404 . Anyways we will only take this up when we have something else to work in PAM and release only with that. Will keep this open.

**Comment by tosan88** [comment]
Is this still valid? @kovacshuni

**Pull request closed without merging**
