### PR TITLE
EOM::Story with "Financial Times" channel is valid for publication.

### PR DESCRIPTION
**Pull request by khatton-ft**
Update PAM to mirror content-importer rules.

### CODE REVIEW

**Comment by tamas-molnar** [comment]
Tests aren't building, please see circleCI build.

**Comment by khatton-ft** [comment]
PEBKAC

**Comment by Nesze** [comment]
👍

**Comment by tamas-molnar** [comment]
+1

**Comment by tosan88** [comment]
:+1:

**Pull request merged**
