### PR TITLE
UP-1038 - articles with non-FT source are eligible for publishing

### PR DESCRIPTION
**Pull request by JuliaFernee**
Articles that have non-FT SourceCode are valid candidates for the publishing stack

### CODE REVIEW

**Comment by Nesze** [comment]
+1

**Comment by kovacshuni** [comment]
+1

**Comment by martingartonft** [comment]
What did I miss?  Why are non-ft source articles eligible for publishing now?

**Comment by kovacshuni** [comment]
Good that you asked.
I was also skeptical. Julia said that dyn pub have fixed a bug in notifications, that was causing errors when these kind of articles were published. So we disabled them for the sake of this bug. But now it's fixed, so we can switch back. This would be the theory.
But i'd really like to confirm with more people, we should have a quick call or just have a word with dyn pubbers if this should really happen.

**Comment by khatton-ft** [comment]
@martingartonft If an article is changed from FT to non-FT source, that change would have been discarded and no delete notification would be written if it is filtered out at the importer.

Previously we were getting spurious delete notifications for non-FT source but as we have agreed not to store deletes when we have no prior knowledge of the content that is no longer an issue.

**Comment by martingartonft** [comment]
@hkatton-ft Okay, I thought it was just that, but the PR title makes this sound more wide ranging.  We still don't actually publish non FT source articles into the db, right?

**Pull request merged**
