### PR TITLE
Godep

### PR DESCRIPTION
**Pull request by Nesze**
Breaking changes in the gonsumer API made this inevitable.

### CODE REVIEW

**Comment by martingartonft** [comment]
Can't we just take the pain of the change once and not use godep?

Or remove godep soon when we can?

I'd like us to look at dependencies more fully at some point, but for the moment avoid any particular solution if we can, especially in light of official solutions being supported properly in the upcoming golang 1.6 (beta1 is out by the way)

**Comment by catalin-ilea** [comment]
I agree, we were planning on switching to the new gonsumer anyway

**Comment by Nesze** [comment]
I'm going to do that, sure.

I wasn't aware of any upcoming official vendor tool and thought godep integrates well with this vendor experiment.

**Comment by Nesze** [comment]
Resolved by https://github.com/Financial-Times/publish-availability-monitor/pull/53

**Pull request closed without merging**
